apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: rbac-manager
  namespace: dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: rbac-manager
  namespace: dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rbac-manager
subjects:
- kind: ServiceAccount
  name: rbac-manager
  namespace: dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: rbac-manager
  namespace: dev
rules:
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - '*'
  verbs:
  - '*'
